name: cleanup
on:
  # push:
  #   branches: ["master"]
  schedule:
    - cron: "00 7 * * *"
    - cron: "30 7 * * *"
    - cron: "00 8 * * *"
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
        - aws
        - azure
        - do
        - gcp
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: dependencies
        run: setup/dependencies.sh
      - name: provider
        run: echo "PROVIDER=${{ matrix.provider }}" >> $GITHUB_ENV
      - name: secrets
        run: setup/secrets.sh
        env:
          SECRETS: ${{ toJson(secrets) }}
      - name: cleanup
        run: provider/${{ matrix.provider }}.sh
